spring:
  application:
    name: inventory-service
  config:
    import: "optional:zookeeper:"
  cloud:
    zookeeper:
      config:
        default-context: gazdabolt
        root: /gazdabolt/config
        profile-separator: "::"
        fail-fast: false
      discovery:
        root: /gazdabolt/services
  data:
    mongodb:
      database: "inventory"
      port: 27017
      host: localhost
      auto-index-creation: true
  graphql:
    schema:
      file-extensions: .graphql,.gql
